% -------------------------------------------------------------------
%  Generated by MATLAB on 19-Feb-2022 15:02:23
%  MATLAB version: 9.11.0.1769968 (R2021b)
% -------------------------------------------------------------------
saveVarsMat = load('SavedVariablesForSimulation.mat');

Airpressure = saveVarsMat.Airpressure; % <1x15000 double> too many elements

Incline = saveVarsMat.Incline; % <1x15000 double> too many elements

Irradiance = saveVarsMat.Irradiance; % <1x15000 double> too many elements

Latitude = saveVarsMat.Latitude; % <15000x1 double> too many elements

Longitude = saveVarsMat.Longitude; % <15000x1 double> too many elements

NextCoordDistance = saveVarsMat.NextCoordDistance; % <1x15000 double> too many elements

Temperature = saveVarsMat.Temperature; % <1x15000 double> too many elements

WVDensity = saveVarsMat.WVDensity; % <1x15000 double> too many elements

clear saveVarsMat;
